Convert to Monorepo
kategengler/ember-cli-code-coverage pull request #289
Opened 2020-09-17 07:18 UTC by Turbo87

😱 😱 😱 😱 

no, wait, hear me out!

This PR is inspired by the repository layout that https://github.com/embroider-build/embroider/ is using. Instead of using the barely maintained https://github.com/tomdale/ember-cli-addon-tests project, we instead use a monorepo layout with several fixture packages in a `test-packages` folder. 

This enables us to use these test fixtures for debugging in a much easier way than before because they can also be used outside of running the test suite. In other words you can `cd` into the folder, run `COVERAGE=true ember test` there and manually verify the results in the `coverage` folder.

It also removes the need for running `npm install` during the test suite because the initial `yarn install` would have already installed all the necessary dependencies. Locally this seems to significantly speed up the test runs, for some reason they still seem to take roughly the same time on CI though.

2020-09-17 13:15 UTC, rwjblue commented
> This PR is inspired by the repository layout that embroider-build/embroider is using. Instead of using the barely maintained tomdale/ember-cli-addon-tests project, we instead use a monorepo layout with several fixture packages in a test-packages folder.

FWIW, `ember-cli-fastboot` did the same general move recently (as did `ember-engines`).

2020-09-17 13:31 UTC, rwjblue requested changes
Some files should be moved back to the project root:

* `CHANGELOG.md`
* `CONTRIBUTING.md`
* `RELEASE.md`

Should add a top level version of these files:

* `README.md` (either duplicating or referencing the main `packages/ember-cli-code-coverage/README.md`)

2020-09-17 13:31 UTC, rwjblue commented on package.json
>    }
Should bring this back, with nearly the same configuration as https://github.com/ember-fastboot/ember-cli-fastboot/pull/783

2020-09-17 13:31 UTC, rwjblue commented on packages/ember-cli-code-coverage/package.json
> +  }
Should be removed (in favor of the changes in https://github.com/ember-fastboot/ember-cli-fastboot/pull/783).

2020-09-17 13:31 UTC, rwjblue commented on test-packages/in-repo-addon-test.js
> +'use strict';
I find it somewhat odd to have this file "loose" in the same directory as other packages.

2020-09-17 13:31 UTC, rwjblue commented on test-packages/in-repo-addon-test.js
> +    await execa('git', ['restore', 'my-app-with-in-repo-addon'], { cwd: __dirname });
Seems vaguely odd to do `git` operations in tests, can you explain what this is cleaning up for?

2020-09-17 13:31 UTC, rwjblue commented on test-packages/my-app-test.js
> +  });
This prelude seems to be repeated a bunch of times, can we make it a util and replace this in each file with:

```js
setupTest(BASE_PATH);
```

2020-09-17 15:28 UTC, kategengler commented on packages/ember-cli-code-coverage/package.json
> +    "test": "npm run-script lint:js && npm run-script node-test"
This tries to run `node-test`, but that's gone

2020-09-17 15:44 UTC, kategengler commented
👍 Very much in favor of this layout, thanks for doing this!

2020-09-21 14:59 UTC, rwjblue commented
Updated to address the various review comments above.

2020-09-21 15:10 UTC, Turbo87 commented
sorry, had it on the todo list, just didn't have time yet 😩

2020-09-21 16:00 UTC, rwjblue approved these changes

2020-09-21 16:00 UTC, merged

2020-09-21 16:00 UTC, rwjblue commented
> sorry, had it on the todo list, just didn't have time yet 😩

No worries! I was just helpin' out 😸